# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UI_MainWindow(object):
    def setupUi(self, UI_MainWindow):
        UI_MainWindow.setObjectName("UI_MainWindow")
        UI_MainWindow.resize(673, 541)
        self.centralwidget = QtWidgets.QWidget(UI_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setMinimumSize(QtCore.QSize(510, 0))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.gridLayout_3.addWidget(self.labelImage, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.btnStart = QtWidgets.QPushButton(self.groupBox)
        self.btnStart.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnStart.setObjectName("btnStart")
        self.gridLayout.addWidget(self.btnStart, 0, 0, 1, 1)
        self.btnPause = QtWidgets.QPushButton(self.groupBox)
        self.btnPause.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnPause.setObjectName("btnPause")
        self.gridLayout.addWidget(self.btnPause, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnLocate = QtWidgets.QPushButton(self.groupBox_2)
        self.btnLocate.setObjectName("btnLocate")
        self.gridLayout_2.addWidget(self.btnLocate, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.btnSplit = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSplit.setObjectName("btnSplit")
        self.gridLayout_2.addWidget(self.btnSplit, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.btnRecoginize = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRecoginize.setObjectName("btnRecoginize")
        self.gridLayout_2.addWidget(self.btnRecoginize, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.editResult = QtWidgets.QTextEdit(self.centralwidget)
        self.editResult.setMaximumSize(QtCore.QSize(80, 16777215))
        self.editResult.setObjectName("editResult")
        self.verticalLayout.addWidget(self.editResult)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 1, 1, 1)
        UI_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UI_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 23))
        self.menubar.setObjectName("menubar")
        self.menu_Open = QtWidgets.QMenu(self.menubar)
        self.menu_Open.setObjectName("menu_Open")
        UI_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_MainWindow)
        self.statusbar.setObjectName("statusbar")
        UI_MainWindow.setStatusBar(self.statusbar)
        self.OpenAction = QtWidgets.QAction(UI_MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../QIcon/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenAction.setIcon(icon)
        self.OpenAction.setObjectName("OpenAction")
        self.menu_Open.addAction(self.OpenAction)
        self.menubar.addAction(self.menu_Open.menuAction())

        self.retranslateUi(UI_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(UI_MainWindow)

    def retranslateUi(self, UI_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_MainWindow.setWindowTitle(_translate("UI_MainWindow", "车牌识别系统"))
        self.groupBox.setTitle(_translate("UI_MainWindow", "视频数据"))
        self.btnStart.setText(_translate("UI_MainWindow", "启动"))
        self.btnPause.setText(_translate("UI_MainWindow", "暂停"))
        self.groupBox_2.setTitle(_translate("UI_MainWindow", "提取步骤"))
        self.btnLocate.setText(_translate("UI_MainWindow", "车牌定位"))
        self.btnSplit.setText(_translate("UI_MainWindow", "字符分割"))
        self.btnRecoginize.setText(_translate("UI_MainWindow", "字符识别"))
        self.label.setText(_translate("UI_MainWindow", "分割结果"))
        self.menu_Open.setTitle(_translate("UI_MainWindow", "File"))
        self.OpenAction.setText(_translate("UI_MainWindow", "Open(&O)"))
        self.OpenAction.setShortcut(_translate("UI_MainWindow", "Ctrl+O"))

